# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY mqtt_publisher.py /app/

# Install any needed packages specified in requirements.txt
RUN pip install paho-mqtt

# Run mqtt_publisher.py when the container launches
CMD ["python", "mqtt_publisher.py"]
